nginxGateway:
  config:
    logging:
      level: error
  gwAPIExperimentalFeatures:
    enable: true
  snippetsFilters:
    enable: true
  replicaCount: 1
nginx:
  config:
    rewriteClientIP:
      mode: ProxyProtocol
      setIPRecursively: true
      trustedAddresses:
        - type: CIDR
          value: 10.0.0.0/8
service:
  create: false
