apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-logs-credentials-test
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-logs-credentials-test
    creationPolicy: Owner
  data:
    - secretKey: username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: grafana-cloud-logs-credentials
        property: username
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore  # or SecretStore
      remoteRef:
        key: grafana-cloud-logs-credentials
        property: password