apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-logs-credentials
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: grafana-cloud-logs-credentials
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-logs-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grafana-cloud-logs-credentials
